authentik:
  postgresql:
    host: authentik-postgresql
    name: authentik
    user: authentik
    password: ""

postgresql:
  enabled: true
  auth:
    username: authentik
    database: authentik
    existingSecret: authentik-secrets
    secretKeys:
      adminPasswordKey: postgresql-password
      userPasswordKey: postgresql-password

redis:
  enabled: true
  auth:
    enabled: false

global:
  envFrom:
    - secretRef:
        name: authentik-secrets
  env:
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-secrets
          key: postgresql-password

server:
  ingress:
    enabled: false
