defaultSettings:
  defaultDataPath: /var/lib/longhorn

preUpgradeChecker:
  jobEnabled: false

longhornManager:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

longhornDriver:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

ingress:
  enabled: false
