apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: f2f83b0e-a6e9-4e76-bea6-b477012140e5 # gitleaks:allow -- Bitwarden secret UUID identifier, not the secret value.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: postgresql-password
      remoteRef:
        key: 677ad03b-9ddd-4cde-9b8d-b47701214104 # gitleaks:allow -- Bitwarden secret UUID identifier, not the secret value.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
