apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: petzko-sh-wildcard
  namespace: traefik
spec:
  secretName: petzko-sh-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - petzko.sh
    - "*.petzko.sh"
