apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: cluster-platform
  source:
    repoURL: git@github.com:petzkod5/rivendell-talos-cluster.git
    targetRevision: main
    path: kubernetes/manifests/coredns
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
