apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-prereqs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: git@github.com:petzkod5/rivendell-talos-cluster.git
    targetRevision: HEAD
    path: kubernetes/manifests/longhorn-prereqs
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
