apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: megascope
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: workloads
  sources:
    - repoURL: ghcr.io/petzkod5/charts
      chart: megascope
      targetRevision: 0.3.0
      helm:
        valueFiles:
          - $values/kubernetes/values/megascope.yaml
    - repoURL: git@github.com:petzkod5/rivendell-talos-cluster.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: megascope
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
