apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petzko-sh-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: git@github.com:petzkod5/petzko.sh.git
    targetRevision: main
    path: charts/petzko-sh
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: petzko-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
